export const ACTIVITY_LOADING = "ACTIVITY_LOADING";

export const ACTIVITY_ADD_SUCCESS = "ACTIVITY_ADD_SUCCESS";
export const ACTIVITY_LIST_SUCCESS = "ACTIVITY_LIST_SUCCESS";
export const ACTIVITY_SINGLE_SUCCESS = "ACTIVITY_SINGLE_SUCCESS";
export const ACTIVITY_DELETE_SUCCESS = "ACTIVITY_DELETE_SUCCESS";
export const ACTIVITY_UPDATE_SUCCESS = "ACTIVITY_UPDATE_SUCCESS";

export const ACTIVITY_ERROR = "ACTIVITY_ERROR";
