export const CUSTOM_FIELD_LOADING = "CUSTOM_FIELD_LOADING";

export const CUSTOM_FIELD_LIST_SUCCESS = "CUSTOM_FIELD_LIST_SUCCESS";
export const CUSTOM_FIELD_ADD_SUCCESS = "CUSTOM_FIELD_ADD_SUCCESS";
export const CUSTOM_FIELD_DELETE_SUCCESS = "CUSTOM_FIELD_DELETE_SUCCESS";
export const CUSTOM_FIELD_ERROR = "CUSTOM_FIELD_ERROR";
