export const POST_LOADING = "POST_LOADING";

export const POST_ADD_SUCCESS = "POST_ADD_SUCCESS";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_SINGLE_SUCCESS = "POST_SINGLE_SUCCESS";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";

export const POST_ERROR = "POST_ERROR";
