export const SUB_ACTIVITY_LOADING = "SUB_ACTIVITY_LOADING";
export const SUB_ACTIVITY_LIST_SUCCESS = "SUB_ACTIVITY_LIST_SUCCESS";
export const SUB_ACTIVITY_ADD_SUCCESS = "SUB_ACTIVITY_ADD_SUCCESS";
export const SUB_ACTIVITY_SINGLE_SUCCESS = "SUB_ACTIVITY_SINGLE_SUCCESS";
export const SUB_ACTIVITY_DELETE_SUCCESS = "SUB_ACTIVITY_DELETE_SUCCESS";
export const SUB_ACTIVITY_UPDATE_SUCCESS = "SUB_ACTIVITY_UPDATE_SUCCESS";
export const SUB_ACTIVITY_ERROR = "SUB_ACTIVITY_ERROR";
