export const USER_LOADING = "USER_LOADING";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_ERROR = "USER_LIST_ERROR";

export const USER_SIGNIN_LOADING = "USER_SIGNIN_LOADING";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_ERROR = "USER_SIGNIN_ERROR";

export const USER_SINGLE_LOADING = "USER_SINGLE_LOADING";
export const USER_SINGLE_SUCCESS = "USER_SINGLE_SUCCESS";
export const USER_SINGLE_ERROR = "USER_SINGLE_ERROR";

export const USER_ERROR = "USER_ERROR";
export const USER_DELETE_LOADING = "USER_DELETE_LOADING";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_STATUS_UPDATE_SUCCESS = "USER_STATUS_UPDATE_SUCCESS";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_ERROR = "USER_DELETE_ERROR";

export const PASSWORD_RESET = "PASSWORD_RESET";

export const USER_LOGOUT = "USER_LOGOUT";
